language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: ./gradlew shadowJar
notifications:
  slack:
    secure: CdGsAr8JnPOj2sKdbTuHunWIOEHb27myvzVpNTeTvd0rVxD5Wq4X2Lns0X31Zh1aXNMIXslV9BdSdy+K9fsie5+98zU24xMYweIoDGvi3ciIVNPA/hZe1ZgMapKVchn91PxFKuzxz1SnkeytKA7vwxdiVzJEPDCx2G3PQWtxxCNql/ndJdLb8WsiyFYQt1f/uURazJa2lqsjr09F7Xzmu6gu8qACSRfzx7ICAZVMCbAkOMbq//IbQcszQoyE7W2G/+GxeXRZMX6S9yRQbaa8mBGn4fTvYhd+hDqvRAPM2VBGy4BPL258KVfYlx43rZ+SWwEBqCQdBOU3HykGhzBrEhwWR9pelIqf7/5Gn0wLxYMEt3STdZssJbzuYFVlZXDGeI/K5eVRFhXXpRwwAt+Ab5oaDIGpWNIOV3hfoCVCBNkIJMwyamOBomjHAQnF6edxvmG6jJvTtQWSR8fjgLD0LReasSZXr8aq+7PzDFOeZqWzSYXTPfsdVKs9n8U2bAVa9DrMObmZ+bJaA3gfwZLOHTqPrYp+JJqeEQEsngw/KJ4VyY0pj09UoJo/WejD56teeXyTNIG4pt0sbofgzWU6xK1QHZp+gMent4qysm/3finYJQzwpLnKGUjLp8boE8PSNv/vru+g2bsZSLvhFMjd9AcDYl6futUdDmZourj1RhY=
deploy:
  provider: releases
  api_key:
    secure: J2ub8wLjfgWDP9LD2SL0PQKHCS/XL6niRGd+jQ8nc10IJcdnsVQm0+Z98oNczTDlWnFo5R52oQK6vgHNxF33a1d6OwgS1KglC7zaB+AeoUdnFjhNc4h+Hf+6Vw2AvBRPVCCOSq4U54RaHlAaGT2KOttW3xYjusLlnBOVaYlPCLpY0SGCFmDp8ssryBMlnEOBaNxP9q4M1PPP4M8Py9bAB5pdJiGzbbJ6DYBMmo26qJOScwaKhqadR55dwuzNY5pFRV8qC0uZYTnkh3T2PqjaiVjD1crCB+AzlHHqzjT0BGufKOAAAjvTuXuuuX8lZiTwxF/vBDMBHRrsxsIbb7YMwSzQyfPQW6hAhpBcwDbbtm0YaNQUfexPq00ydBiWIjpxgTMYmf+GQxUj22ghpXQjCGwNfsw/ioo8zx2H2/HbvzFOWUwhhMzD4PGBEjcZ5f/EILJGBUgZzjIu6r3ixSoX/jcihs3yN3+3jbbJOuV7DAGd2o9Ji+4+vrSRhBYQwljY7wZRtvaj0y0M5Pjr9DKMRphk07MjoraDLIcDEPwn6VZIUH6V3MxK8i6sF0m1IIK4lkTrSEeTNCj1Li6FEE+H0SYtP1XBjKfBrCwtmy9+cMWqrZ76LDaJhEWq0BMw7nRcXvjGcpluu0UFKFdg3S9UqdaiSqenBVwhCZiXLTUc32w=
  file: build/libs/MazeStuff-1.0-SNAPSHOT-all.jar
  skip_cleanup: true
  on:
    tags: true
