language: java
before_install:
 - chmod +x gradlew
jdk:
 - oraclejdk8
script: ./gradlew shadowJar
deploy:
  provider: releases
  api_key: d89f42f0f3fb6341aea3cad705272ae8386caecf
  file: "build/libs/MazeStuff-1.0-SNAPSHOT-all.jar"
  skip_cleanup: true
  on:
    tags: true